SwasiHealthCare/SwasiHealthCare.Service/Controllers/PatientController.cs
using SwasiHealthCare.BusinessManager;
using SwasiHealthCare.Data.Entities;
using SwasiHealthCare.IBusinessManager;
using SwasiHealthCare.Model;
using SwasiHealthCare.Repository;
using SwasiHealthCare.Service.Helper;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using static SwasiHealthCare.Service.FilterConfig;

namespace SwasiHealthCare.Service.Controllers
{
    public class PatientController : Controller
    {
        [HttpGet]
        [Gzip]
        public async Task<ActionResult> Index()
        {
            if (Session["UserId"] == null || Session["UserId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }

            if (Session["RoleId"] == null || Session["RoleId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }
            long? hospitalid = Convert.ToInt64(Session["HospitalId"]);
            try
            {
                IPatientManager patientmanager = new PatientManager();
                var patientlist = await ViewHelper.GetAllPatients();
                foreach (var item in patientlist)
                {
                    if (item.FilePath != null && item.FilePath != string.Empty)
                    {
                        var documentlist = await ViewHelper.GetAllDocumentById(item.PatientId ?? 0);
                        item.PatientDocumentList = documentlist;
                    }
                }
                patientlist = patientlist.OrderByDescending(x => x.PatientRegisterNumber)
                    .Where(x=>x.PatientHospitalId == hospitalid).ToList();
                return View(patientlist);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpGet]
        [Gzip]
        public async Task<ActionResult> NewPatient()
        {
            if (Session["UserId"] == null || Session["UserId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }

            if (Session["RoleId"] == null || Session["RoleId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }

            try
            {
                long userid = Convert.ToInt64(Session["UserId"]);
                IUserManager userManager = new UserManager();
                IHospitalManager hospitalManager = new HospitalManager();
                var userdetails = (await userManager.GetEditUser(userid));
                var hospitaldetails = await hospitalManager.GetEditHospital(userdetails.HospitalId ?? 0);
                List<PlanModel> planlist = await ViewHelper.GetAllPlan();
                List<PatientModel> paientlist = (await ViewHelper.GetAllPatients()).Where(x=>x.PatientHospitalId == userdetails.HospitalId).ToList();
                ViewBag.planlist = planlist;
                List<Hospital> hospital = (await userManager.GetHospitals()).ToList();
                ViewBag.hospitallist = hospital;
                IPatientManager patientmanager = new PatientManager();
               
                List<UserModel> doctorlist = (await ViewHelper.GetAllUsers()).Where(x => x.RoleId == 3).ToList();
                if (hospitaldetails.PatientIdStartWith == string.Empty || hospitaldetails.PatientIdStartWith == null)
                {
                    ViewBag.doctorlist = doctorlist;
                    ViewBag.planlist = planlist;
                    ViewBag.hospitallist = hospital;
                    ViewBag.PatientIdStartWith = "Please create patient id start with settings hospital menu!.";
                    return View();
                }
                ViewBag.doctorlist = doctorlist;
                var patientcount = patientmanager.GetPatientsCount(userdetails.HospitalId ?? 0);
                var opidnumber = patientcount + 1;
                return View(new Model.PatientModel { PatientIdNumber = hospitaldetails.PatientIdStartWith + "-" + opidnumber ,PatientRegisterNumber = opidnumber });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        [Gzip]
        public async Task<ActionResult> NewPatient(PatientModel patientModel)
        {
            if (Session["UserId"] == null || Session["UserId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }

            if (Session["RoleId"] == null || Session["RoleId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }

            try
            {
                long? hospitalid = Convert.ToInt64(Session["HospitalId"]);
                long userid = Convert.ToInt64(Session["UserId"]);
                IUserManager userManager = new UserManager();
                var usedetails = userManager.GetLoginUserDetails(userid);
                var doctotdetails = (await userManager.GetEditUser(patientModel.PatientDoctorId ?? 0));
                IPatientManager patientManager = new PatientManager();
                patientModel.PatientCreatedBy = Convert.ToInt64(Session["UserId"]);
                patientModel.PatientStatus = true;
                patientModel.PatientHospitalId = hospitalid;
                if (patientModel.PatientId == 0 || patientModel.PatientId == null)
                {
                    patientModel.Mode = "A";
                    patientModel.PatientDoctorName = doctotdetails?.FullName;
                }
                else
                {
                    patientModel.PatientDoctorName = doctotdetails?.FullName;
                    patientModel.Mode = "E";
                }
                var result = await patientManager.SavePatient(patientModel);
                if (Request.Files.Count > 0)
                {
                    for (int i = 0; i < Request.Files.Count; i++)
                    {
                        var patientidnumber = await patientManager.GetEditPatient(patientModel.PatientId ?? 0);
                        HttpPostedFileBase file = Request.Files[i];
                        int fileSize = file.ContentLength;
                        if (fileSize > 0)
                        {
                            FileInfo fileinfo = new FileInfo(file.FileName);
                            var folderName = patientidnumber.PatientIdNumber;
                            byte[] fileByteArray = new byte[fileSize];
                            file.InputStream.Read(fileByteArray, 0, fileSize);
                            string fileLocation = Path.Combine(Server.MapPath("~/Content/Files/PatientReports/" + folderName), fileinfo.Name);
                            if (!Directory.Exists(Path.Combine(Server.MapPath("~/Content/Files/PatientReports/" + folderName))))
                                Directory.CreateDirectory(Path.Combine(Server.MapPath("~/Content/Files/PatientReports/" + folderName)));
                            file.SaveAs(fileLocation);

                            patientModel.FilePath = "File";
                            patientModel.Mode = "E";
                            await patientManager.SavePatient(patientModel);

                            var patientdocument = new PatientDocument 
                            {
                                PatientId = patientidnumber.PatientId,
                                FileName = fileinfo.Name,
                                FolderName = folderName,
                                PatientIdNumber = patientidnumber.PatientIdNumber,
                                DocumentCreatedBy= patientModel.PatientCreatedBy,
                                DocumentCreatedDate = DateTime.Now
                            };
                            await patientManager.SavePatientDocumnet(patientdocument);
                        }
                    }
                }
                //return Json(result);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public async Task<ActionResult> PatientStatus(long patientid, bool status)
        {
            try
            {
                IPatientManager patientManager = new PatientManager();
                var result = await patientManager.UpdatePatientStatus(patientid, status, Convert.ToInt64(Session["UserId"]));
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        [Gzip]
        public async Task<ActionResult> EditPatient(long patientid)
        {
            if (Session["UserId"] == null || Session["UserId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }

            if (Session["RoleId"] == null || Session["RoleId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }

            try
            {
                IUserManager userManager = new UserManager();
                List<PlanModel> planlist = await ViewHelper.GetAllPlan();
                List<PatientModel> paientlist = await ViewHelper.GetAllPatients();
                List<Hospital> hospital = (await userManager.GetHospitals()).ToList();
                ViewBag.planlist = planlist;
                ViewBag.hospitallist = hospital;
                IPatientManager patientMagager = new PatientManager();
                var users = (await patientMagager.GetEditPatient(patientid));
                List<UserModel> doctorlist = (await ViewHelper.GetAllUsers()).Where(x => x.RoleId == 3).ToList();

SwasiHealthCare/SwasiHealthCare.Service/Views/Patient/Index.cshtml
@model List<SwasiHealthCare.Model.PatientModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
    List<SwasiHealthCare.Data.Entities.AccessRights> rights =
     (List<SwasiHealthCare.Data.Entities.AccessRights>)Session["AccessRights"];
    var roleid = Convert.ToInt64(Session["RoleId"]);
}
<div class="row clearfix">
    <div class="col-sm-12">
        <div class="card">
            <div class="body">
                <form>
                    <div class="input-group" style="width:900px">
                        <input type="text" class="form-control" id="searchpatient" placeholder="Search here...">
                        <div class="input-group-append">
                            <span class="input-group-text" id="search-mail"><i class="icon-magnifier"></i></span>
                        </div>
                        @if ((roleid == 4 || roleid == 3) && rights.Where(x => x.MenuId == 1 && x.IsCreate).Any())
                        {
                            <div id="z_button" tabindex="0">
                                <div id="z_plus"><a href="@Url.Action("NewPatient", "Patient")"><span style="color:#ffffff">+</span></a></div>
                            </div>
                        }
                        else if (roleid != 4 && roleid != 3)
                        {
                            <div id="z_button" tabindex="0">
                                <div id="z_plus"><a href="@Url.Action("NewPatient", "Patient")"><span style="color:#ffffff">+</span></a></div>
                            </div>
                        }
                        </div>
                </form>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover table-custom spacing5" id="patient_list">
                <thead>
                    <tr>
                        <th>#</th>
                        <th> ID Number </th>
                        <th> Gender </th>
                        <th style="width:80px"> Name </th>
                        <th> Age </th>
                        <th style="width:345px; word-break:break-all "> Address </th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        var index = 1;
                        foreach (var item in Model)
                        {
                            <tr style="animation: none; opacity: 1;transform: none;" wi>
                                <td>@index</td>
                                <td>@item.PatientIdNumber</td>
                                <td class="w60">
                                    @if (item.PatientGender == "M")
                                    {
                                        <img src="~/Theme/Html/assets/images/xs/avatar4.jpg" data-toggle="tooltip" data-placement="top" title="" alt="Avatar" class="avatar rounded-circle" data-original-title="Male">
                                    }
                                    else
                                    {
                                        <img src="~/Theme/Html/assets/images/xs/avatar3.jpg" data-toggle="tooltip" data-placement="top" title="" alt="Avatar" class="avatar rounded-circle" data-original-title="Female">
                                    }
                                </td>
                                <td>@item.PatientName<div>@item.PatientMobileNumber</div><div>@item.PatientWhatsappNumber</div></td>
                                <td>@item.PatientAge</td>
                                <td>@item.PatientAddress</td>
                                <td>
                                    @if (item.PatientStatus)
                                    {
                                        <button type="button" class="btn btn-default btn-sm" onclick="ChangePatientStatus(@item.PatientId,true)" style="color:#82b440; cursor:pointer" ; data-toggle="modal" data-target="#exampleModalCenter" title="Change User Status"><i class="fa fa-check-circle"></i></button>
                                    }
                                    else
                                    {
                                        <button type="button" class="btn btn-default btn-sm" onclick="ChangePatientStatus(@item.PatientId,true)" style="color:#FF2A2A;cursor:pointer" ; data-toggle="modal" data-target="#exampleModalCenter" title="Change User Status"><i class="fa fa-times-circle"></i></button>
                                    }
                                    @if ((roleid == 4 || roleid == 3) && rights.Where(x => x.MenuId == 1 && x.IsEdit).Any())
                                    {
                                        <button onclick="location.href='@Url.Action("EditPatient", "Patient", new { patientid = item.PatientId })'" ; type="button" style="color:#0094ff; cursor:pointer" ; class="btn btn-default btn-sm" title="Edit"><i class="fa fa-pencil"></i></button>
                                    }
                                    else if (roleid == 2)
                                    {
                                        <button onclick="location.href='@Url.Action("EditPatient", "Patient", new { patientid = item.PatientId })'" ; type="button" style="color:#0094ff; cursor:pointer" ; class="btn btn-default btn-sm" title="Edit"><i class="fa fa-pencil"></i></button>
                                    }
                                    @if ((roleid == 4 || roleid == 3) && rights.Where(x => x.MenuId == 1 && x.IsDelete).Any())
                                    {
                                        <button type="button" style="color: #3e062d; cursor:pointer" ; class="btn btn-default btn-sm" title="Delete" onclick="RemovePatient(@item.PatientId)" data-toggle="modal" data-target="#exampleModalCenter"><i class="fa fa-trash-o"></i></button>
                                    }
                                    else if (roleid == 2)
                                    {
                                        <button type="button" style="color: #3e062d; cursor:pointer" ; class="btn btn-default btn-sm" title="Delete" onclick="RemovePatient(@item.PatientId)" data-toggle="modal" data-target="#exampleModalCenter"><i class="fa fa-trash-o"></i></button>
                                    }
                                    @if (item.FilePath != null && item.FilePath != string.Empty)
                                    {
                                        <ul class="nav navbar-nav">
                                            <li class="dropdown hidden-xs">
                                                <a href="javascript:void(0);" class="dropdown-toggle icon-menu" data-toggle="dropdown">
                                                    <button type="button" class="btn btn-default btn-sm" onclick="" style="color:#b200ff;cursor:pointer" ;><i class="fa fa-files-o"></i></button>
                                                    <span class="notification-dot msg">@item.PatientDocumentList.Count() </span>
                                                </a>
                                                <ul class="dropdown-menu right_chat email mt-0 animation-li-delay">
                                                    <li class="header theme-bg gradient mt-0 text-light">The patient @item.PatientIdNumber have @item.PatientDocumentList.Count() document</li>
                                                    <li>
                                                        @foreach (var doc in item.PatientDocumentList)
                                                        {
                                                            <a href="javascript:void(0);">
                                                                <div class="media">
                                                                    <div class="media-body">
                                                                        <span class="name">@doc.FileName<small class="float-right font-12">@doc.DocumentCreatedDate.ToString("MM/dd/yyyy")</small><i class="fa fa-download" onclick="location.href='@Url.Action("DownloadPatient", "Patient", new { documentid = doc.DocumentId })'" ;></i></span>
                                                                        <span class="message"></span>
                                                                    </div>
                                                                </div>
                                                            </a>
                                                        }
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    }
                                </td>
                            </tr>
                            index++;
                        }
                    }
                </tbody>
                
            </table>
                </div>
    </div>
</div>
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" style="border-radius: 9px;">
            <div class="modal-header">
                <div><h6 class="modal-title" id="exampleModalCenterTitle"></h6></div>
            </div>
            <div class="modal-body">
                <div id="confirmmsg"></div>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-outline-primary borderradius" id="ActionStatus" onclick="PatientStatus()">Save changes</a>
                <a href="#" class="btn btn-outline-primary borderradius" id="ActionDelete" onclick="DeletePatient()">Save changes</a>
                <a href="@Url.Action("Index", "Patient")" class="btn btn-outline-secondary borderradius">Close</a>
                <input type="hidden" id="hiddenpatientid" />
                <input type="hidden" id="hiddenstatus" />
            </div>
        </div>
    </div>
</div>
@section scripts {
<script src="~/Scripts/Patient/Patient.js"></script>
    <script>
        $(document).ready(function () {
            $("#patient").trigger("click");
            $("#allpatient").addClass("active");
            $("#page_name").text("Patient Details,");

            $("#searchpatient").on("keyup", function () {
                var value = $(this).val();
                $("table tr").each(function (index) {
                    if (index !== 0) {
                        $row = $(this);
                        var id = $row.find("td:eq(3)").text();
                        //alert(id);
                        if (id.toLowerCase().indexOf(value.toLowerCase()) !== 0) {
                            $row.hide();
                        }
                        else {
                            $row.show();
                        }
                    }
                });
            });

            //$("#searchpatient").on("keyup", function () {
            //    var value = $(this).val();
            //    $("table tr").each(function (index) {
            //        if (index != 0) {
            //            $row = $(this);
            //            var id = $row.find("td:eq(1)").text();
            //            if (id.indexOf(value) != 0) {
            //                $(this).hide();
            //            }
            //            else {
            //                $(this).show();
            //            }
            //        }
            //    });
            //});
        });
    </script>}

SwasiHealthCare/SwasiHealthCare.Service/Views/Patient/OPDIndex.cshtml
@model List<SwasiHealthCare.Model.OPDConsoltationModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
    List<SwasiHealthCare.Data.Entities.AccessRights> rights =
      (List<SwasiHealthCare.Data.Entities.AccessRights>)Session["AccessRights"];
    var roleid = Convert.ToInt64(Session["RoleId"]);
    var amnt = 0;
}
<div class="row clearfix">
    <div class="col-sm-12">
        <div class="card">
            <div class="body">
                <form>
                    <div class="input-group" style="width:900px">
                        <input type="text" class="form-control" id="searchopd" placeholder="Search here...">
                        <div class="input-group-append">
                            <span class="input-group-text" id="search-mail"><i class="icon-magnifier"></i></span>
                        </div>
                        @if ((roleid == 4 || roleid == 3) && rights.Where(x => x.MenuId == 2 && x.IsCreate).Any())
                        {
                            <div id="z_button" tabindex="0">
                                <div id="z_plus"><a href="@Url.Action("NewOPD", "Patient")"><span style="color:#ffffff">+</span></a></div>
                            </div>
                        }
                        else if (roleid == 2)
                        {
                            <div id="z_button" tabindex="0">
                                <div id="z_plus"><a href="@Url.Action("NewOPD", "Patient")"><span style="color:#ffffff">+</span></a></div>
                            </div>
                        }
                    </div>
                </form>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover table-custom spacing5">
                <thead>
                    <tr>
                        <th>#</th>
                        <th> Date </th>
                        <th> OPD Id </th>
                        <th> Patient Name </th>
                        <th> Nature of Illness </th>
                        <th> Total Amount </th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        var index = 1;
                        foreach (var item in Model)
                        {
                    <tr>
                        <td>@index</td>
                        @*<td class="w60">
                        @if (item.PatientGender == "M")
                        {
                        <img src="~/Theme/Html/assets/images/xs/avatar4.jpg" data-toggle="tooltip" data-placement="top" title="" alt="Avatar" class="avatar rounded-circle" data-original-title="Male">
                        }
                        else
                        {
                        <img src="~/Theme/Html/assets/images/xs/avatar3.jpg" data-toggle="tooltip" data-placement="top" title="" alt="Avatar" class="avatar rounded-circle" data-original-title="Female">
                        }
                        </td
                        <td>
                        <a href="javascript:void(0);" title=""> @item.PatientName</a>
                        <div>@item.PatientIDNumber</div>
                        <div>@item.PatientMobileNo</div>
                        </td>
                        <td>@item.DoctorName</td>
                        <td>@item.DoctorsNote</td>
                        <td>@item.NatureOfIllness</td>*@
                        <td>@item.ConsultationDate.ToString("dd/MM/yyyy")</td>
                        <td>@item.ConsultationIDNumber</td>
                        <td>@item.PatientName - @item.PatientIDNumber</td>
                        <td>@item.NatureOfIllness</td>
                        @*@amnt = @item.TreatmentSplDiscount == 0 ? @item.TreatmentTotalServicesCharges : @item.TreatmentSplDiscount*@
                        <td>  @item.NetCharges</td>
                        <td>
                            <button onclick="location.href='@Url.Action("NewOPD", "Patient", new { opdconsutationid = item.OPDConsultationId, patientidnumber = item.PatientIDNumber })'" ; type="button" style="color:#0094ff; cursor:pointer" ; class="btn btn-default btn-sm" title="View"><i class="fa fa-eye"></i></button>
                            @* <button onclick="window.location.href = '@Url.Action("NewOPD", "Patient",new { opdconsutationid =1} )'"></button>*@
                        </td>
                        @*<td>
                            <button type="button" style="color:#0094ff; cursor:pointer" ; class="btn btn-default btn-sm" title="View"id="btnUpdateAmt"><i class="fa fa-eye"></i></button>
                        </td>*@
                          </tr>
                                index++;
                            }
                        }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" style="border-radius: 9px;">
            <div class="modal-header">
                <div><h6 class="modal-title" id="exampleModalCenterTitle"></h6></div>
            </div>
            <div class="modal-body">
                <div id="confirmmsg"></div>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-outline-primary borderradius" id="ActionStatus" onclick="UserStatus()">Save changes</a>
                <a href="#" class="btn btn-outline-primary borderradius" id="ActionDelete" onclick="DeleteUser()">Save changes</a>
                <a href="@Url.Action("Index", "User")" class="btn btn-outline-secondary borderradius">Close</a>
                <input type="hidden" id="hiddenuserid" />
                <input type="hidden" id="hiddenstatus" />
            </div>
        </div>
    </div>
</div>
@section scripts {
    <script>
        $(document).ready(function () {
            $("#page_name").text("OPD Details,");
            $("#opd").trigger("click");
            $("#allopd").addClass("active");
            $("#searchopd").on("keyup", function () {
                var value = $(this).val();
                $("table tr").each(function (index) {
                    if (index != 0) {
                        $row = $(this);
                        var id = $row.find("td:eq(3)").text();
                        if (id.toLowerCase().indexOf(value.toLowerCase()) != 0) {
                            $(this).hide();
                        }
                        else {
                            $(this).show();
                        }
                    }
                });
            });
        });
    </script>}