SwasiHealthCare/SwasiHealthCare.Service/Controllers/DesignationController.cs
using SwasiHealthCare.BusinessManager;
using SwasiHealthCare.Data.Entities;
using SwasiHealthCare.IBusinessManager;
using SwasiHealthCare.Model;
using SwasiHealthCare.Service.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using static SwasiHealthCare.Service.FilterConfig;

namespace SwasiHealthCare.Service.Controllers
{
    public class DesignationController : Controller
    {
        public DesignationController()
        {

        }
        [HttpGet]
        [Gzip]
        public async Task<ActionResult> Index()
        {
            if (Session["UserId"] == null || Session["UserId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }
            if (Session["RoleId"] == null || Session["RoleId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }
            try
            {
                var designationlist = await ViewHelper.GetAllDesignation();
                return View(designationlist);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost] 
        public async Task<ActionResult> NewDesignation(DesignationModel designationModel)
        {
            try
            {
                IDesignationManager designationManager = new DesignationManager();
                designationModel.DesignationCreatedBy = Convert.ToInt64(Session["UserId"]);
                designationModel.DesignationStatus = true;
                long? hospitalid = Convert.ToInt64(Session["HospitalId"]);
                if (designationModel.DesignationId != null)
                {
                    designationModel.HospitalId = hospitalid;
                    designationModel.Mode = "E";
                }
                else
                {
                    
                    designationModel.HospitalId = hospitalid;
                    designationModel.Mode = "A";
                }
                var result = await designationManager.AddNewDesignation(designationModel);
                return Json(result);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        [Gzip]
        public async Task<ActionResult> EditDesignation(long designationid)
        {
            try
            {
                IDesignationManager designationManager = new DesignationManager();
                var designation = (await designationManager.GetEditDesignation(designationid));
                return View(designation);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public async Task<ActionResult> EditDesignation(DesignationModel designationModel)
        {
            try
            {
                IDesignationManager designationManager = new DesignationManager();
                designationModel.DesignationModifiedBy = Convert.ToInt64(Session["UserId"]);
                designationModel.Mode = "E";
                await designationManager.AddNewDesignation(designationModel);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public async Task<ActionResult> DeleteDesignation(long designationid)
        {
            try
            {
                IDesignationManager designationManager = new DesignationManager();
                var result = await designationManager.DeleteDesignation(designationid);
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public async Task<ActionResult> DesignationStatus(long designationid, bool status)
        {
            try
            {
                IDesignationManager designationManager = new DesignationManager();
                var result = await designationManager.UpdateDesignationStatus(designationid, status, Convert.ToInt64(Session["UserId"]));
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

SwasiHealthCare/SwasiHealthCare.Service/Views/Designation/Index.cshtml
@model List<SwasiHealthCare.Model.DesignationModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
    List<SwasiHealthCare.Data.Entities.AccessRights> rights =
    (List<SwasiHealthCare.Data.Entities.AccessRights>)Session["AccessRights"];
    var roleid = Convert.ToInt64(Session["RoleId"]);
}
<div class="row clearfix">
    <div class="col-sm-12">
        <div class="card">
            <div class="body">
                <form>
                    <div class="input-group" style="width:900px">
                        <input type="text" class="form-control" id="search-date" placeholder="Search here...">
                        <div class="input-group-append">
                            <span class="input-group-text" id="search-mail"><i class="icon-magnifier"></i></span>
                        </div>
                        @if ((roleid == 4 || roleid == 3) && rights.Where(x => x.MenuId == 10 && x.IsCreate).Any())
                        {
                            <div id="z_button" tabindex="0">
                                <div id="z_plus"><a data-toggle="modal" data-target="#exampleModalCenterAddDesig"><span style="color:#ffffff">+</span></a></div>
                            </div>
                        }
                        else if (roleid == 1 || roleid == 2)
                        {
                            <div id="z_button" tabindex="0">
                                <div id="z_plus"><a data-toggle="modal" data-target="#exampleModalCenterAddDesig"><span style="color:#ffffff">+</span></a></div>
                            </div>
                        }
                    </div>
                </form>
            </div>
        </div>
        <div class="table-responsive" id="designation_list">
            <table class="table table-hover table-custom spacing5" id="des_tble">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Designation Name</th>
                        <th>Created Date</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                            var index = 1;
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>@index</td>
                                <td>@item.DesignationName</td>
                                <td>@item.DesignationCreatedDate.ToString("MM/dd/yyyy")</td>
                                <td>
                                    @if (item.DesignationStatus)
                                    {
                                        <button type="button" class="btn btn-default btn-sm" onclick="ChangeDesignationStatus(@item.DesignationId,false)" style="color:#82b440; cursor:pointer" ; data-toggle="modal" data-target="#exampleModalCenter" title="Change User Status"><i class="fa fa-check-circle"></i></button>
                                    }
                                    else
                                    {
                                        <button type="button" class="btn btn-default btn-sm" onclick="ChangeDesignationStatus(@item.DesignationId,true)" style="color:#FF2A2A;cursor:pointer" ; data-toggle="modal" data-target="#exampleModalCenter" title="Change User Status"><i class="fa fa-times-circle"></i></button>
                                    }
                                    @if ((roleid == 4 || roleid == 3) && rights.Where(x => x.MenuId == 10 && x.IsEdit).Any())
                                    {
                                        <button type="button" style="color:#0094ff; cursor:pointer" ; class="btn btn-default btn-sm" title="Edit" onclick="EditExistDesignation(@item.DesignationId,'@item.DesignationName')" data-toggle="modal" data-target="#exampleModalCenterAddDesig"><i class="fa fa-pencil"></i></button>
                                    }
                                    else if (roleid == 1 || roleid == 2)
                                    {
                                        <button type="button" style="color:#0094ff; cursor:pointer" ; class="btn btn-default btn-sm" title="Edit" onclick="EditExistDesignation(@item.DesignationId,'@item.DesignationName')" data-toggle="modal" data-target="#exampleModalCenterAddDesig"><i class="fa fa-pencil"></i></button>
                                    }
                                    @if ((roleid == 4 || roleid == 3) && rights.Where(x => x.MenuId == 10 && x.IsDelete).Any())
                                    {
                                        <button type="button" style="color: #3e062d; cursor:pointer" ; class="btn btn-default btn-sm" title="Delete" onclick="RemoveDesignation(@item.DesignationId)" data-toggle="modal" data-target="#exampleModalCenter"><i class="fa fa-trash-o"></i></button>
                                    }
                                    else if (roleid ==1 || roleid==2)
                                    {
                                        <button type="button" style="color: #3e062d; cursor:pointer" ; class="btn btn-default btn-sm" title="Delete" onclick="RemoveDesignation(@item.DesignationId)" data-toggle="modal" data-target="#exampleModalCenter"><i class="fa fa-trash-o"></i></button>
                                    }
                                </td>
                            </tr>
                            index++;
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" style="border-radius: 9px;">
            <div class="modal-header">
                <div><h6 class="modal-title" id="exampleModalCenterTitle"></h6></div>
            </div>
            <div class="modal-body">
                <div id="confirmmsg"></div>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-outline-primary borderradius" id="ActionStatus" onclick="DesignationStatus()">Save changes</a>
                <a href="#" class="btn btn-outline-primary borderradius" id="ActionDelete" onclick="DeleteDesignation()">Save changes</a>
                <a href="@Url.Action("Index", "Designation")" class="btn btn-outline-secondary borderradius">Close</a>
                <input type="hidden" id="hiddendesignationid" />
                <input type="hidden" id="hiddenstatus" />
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="exampleModalCenterAddDesig" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" style="border-radius: 9px;">
            <div class="modal-header">
                <div><h6 class="modal-title" id=""> Add Designation </h6></div>
            </div>
            <div class="modal-body">
                <div id="">
                    <label>Designation Name</label><span style="padding-left:2px;color:red">*</span>
                    <input type="text" id="DesignationName" class="form-control input-default borderclr" />
                </div>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-outline-primary borderradius" onclick="DesignationAdd()">Save changes</a>
                <a href="@Url.Action("Index", "Designation")" class="btn btn-outline-secondary borderradius">Close</a>
                <input type="hidden" id="hiddendesignationid" />
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/Scripts/Designation/Designation.js"></script>
    <script>
        $(document).ready(function () {
            $("#page_name").text("Designation Details,");

            $("#search-date").on("keyup", function () {
                var value = $(this).val();

                $("table tr").each(function (index) {
                    debugger;
                    if (index != 0) {

                        $row = $(this);

                        //var id = $row.find("td:first").text();
                        var id = $row.find("td:eq(1)").text();

                        if (id.toLowerCase().indexOf(value.toLowerCase()) != 0) {
                            $(this).hide();
                        }
                        else {
                            $(this).show();
                        }
                    }
                });
            });

        });
    </script>
}