SwasiHealthCare/SwasiHealthCare.Service/Controllers/HospitalController.cs
using SwasiHealthCare.BusinessManager;
using SwasiHealthCare.Data.Entities;
using SwasiHealthCare.IBusinessManager;
using SwasiHealthCare.Model;
using SwasiHealthCare.Service.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using static SwasiHealthCare.Service.FilterConfig;
namespace SwasiHealthCare.Service.Controllers
{
    public class HospitalController : Controller
    {
        public HospitalController()
        {

        }

        [HttpGet]
        [Gzip]
        public async Task<ActionResult> Index()
        {
            if (Session["UserId"] == null || Session["UserId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }

            if (Session["RoleId"] == null || Session["RoleId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }

            try
            {
                var hospitallist = await ViewHelper.GetAllHospital();
                return View(hospitallist);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpGet]
        [Gzip]
        public async Task<ActionResult> NewHospital()
        {
            if (Session["UserId"] == null || Session["UserId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }

            if (Session["RoleId"] == null || Session["RoleId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }
            try
            {
                IHospitalManager hospitalManager = new HospitalManager();
                return View(new Model.HospitalModel());
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public async Task<ActionResult> NewHospital(HospitalModel hospitalModel)
        {
            if (Session["UserId"] == null || Session["UserId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }

            if (Session["RoleId"] == null || Session["RoleId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }
            try
            {
                IHospitalManager hospitalManager = new HospitalManager();
                hospitalModel.HospitalCreatedBy = Convert.ToInt64(Session["UserId"]);
                hospitalModel.HospitalStatus = true;
                hospitalModel.Mode = "A";
                var result = await hospitalManager.AddHospital(hospitalModel);
                return RedirectToAction("Index", result);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        [Gzip]
        public async Task<ActionResult> EditHospital(long hospitalid)
        {
            if (Session["UserId"] == null || Session["UserId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }

            if (Session["RoleId"] == null || Session["RoleId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }
            try
            {
                IHospitalManager hospitalManager = new HospitalManager();
                var hospital = (await hospitalManager.GetEditHospital(hospitalid));
                return View(hospital);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public async Task<ActionResult> EditHospital(Model.HospitalModel hospitalModel)
        {
            if (Session["UserId"] == null || Session["UserId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }

            if (Session["RoleId"] == null || Session["RoleId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }
            try
            {
                IHospitalManager hospitalManager = new HospitalManager();
                hospitalModel.HospitalModifiedBy = Convert.ToInt64(Session["UserId"]);
                hospitalModel.Mode = "E";
                await hospitalManager.AddHospital(hospitalModel);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public async Task<ActionResult> DeleteHospital(long hospitalid)
        {
            if (Session["UserId"] == null || Session["UserId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }

            if (Session["RoleId"] == null || Session["RoleId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }
            try
            {
                IHospitalManager hospitalManager = new HospitalManager();
                var result = await hospitalManager.DeleteHospital(hospitalid);
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public async Task<ActionResult> HospitalStatus(long hospitalid, bool status)
        {
            if (Session["UserId"] == null || Session["UserId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }

            if (Session["RoleId"] == null || Session["RoleId"].ToString() == string.Empty)
            {
                return RedirectToAction("Login", "Home");
            }
            try
            {
                IHospitalManager hospitalManager = new HospitalManager();
                var result = await hospitalManager.UpdateHospitalStatus(hospitalid, status, Convert.ToInt64(Session["UserId"]));
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

SwasiHealthCare/SwasiHealthCare.Service/Views/Hospital/EditHospital.cshtml
@model SwasiHealthCare.Model.HospitalModel
@{
    ViewBag.Title = "New Hospital";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<html>
<head>
</head>
<body>
    <div class="card w-100 shadow-sm border-0">
        <div class="card-body p-3">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div>
                    <div class="tab-content" id="nav-tabContent">
                        <div class="" id="nav-newsystem" role="tabpanel" aria-labelledby="nav-orginal-tab" style="overflow-y: auto;">
                            <div class="card-body">
                                @Html.HiddenFor(model=>model.HospitalId)
                                <div class="form-row">
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                                        <i class="fa fa-sort-numeric-asc" aria-hidden="true"></i>
                                        @Html.Label("HospitalCode", "Hospital Code")<span style="padding-left:2px;color:red">*</span>
                                        @Html.TextBoxFor(model => model.HospitalCode, new { @class = "form-control input-default borderclr", Maxlength = 20, id = "txthospitalcode" })
                                        @Html.ValidationMessageFor(model => model.HospitalCode, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                                        <i class="fa fa-address-book" aria-hidden="true"></i>
                                        @Html.Label("HospitalName", "Hospital Name")<span style="padding-left:2px;color:red">*</span>
                                        @Html.TextBoxFor(model => model.HospitalName, new { @class = "form-control input-default borderclr", Maxlength = 30, id = "txthospitalname" })
                                        @Html.ValidationMessageFor(model => model.HospitalName, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                                        <i class="fa fa-phone" aria-hidden="true"></i>
                                        @Html.Label("HospitalMobilNumber", "Mobil Number")<span style="padding-left:2px;color:red">*</span>
                                        @Html.TextBoxFor(model => model.HospitalMobilNumber, new { @class = "form-control input-default borderclr", Maxlength = 10, id = "txthospitalmobilnumber" })
                                        @Html.ValidationMessageFor(model => model.HospitalMobilNumber, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                                        <i class="fa fa-mobile" aria-hidden="true"></i>
                                        @Html.Label("LandlineNumber", "Landline Number")
                                        @Html.TextBoxFor(model => model.LandlineNumber, new { @class = "form-control input-default borderclr", Maxlength = 10, id = "txtlandlinenumber" })
                                        @Html.ValidationMessageFor(model => model.LandlineNumber, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                                        <i class="fa fa-navicon" aria-hidden="true"></i>
                                        @Html.Label("HospitalContactPersonName", "Contact Person Name")<span style="padding-left:2px;color:red">*</span>
                                        @Html.TextBoxFor(model => model.HospitalContactPersonName, new { @class = "form-control input-default borderclr", Maxlength = 30, id = "txthospitalcontactpersonname" })
                                        @Html.ValidationMessageFor(model => model.HospitalContactPersonName, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                                        <i class="fa fa-envelope" aria-hidden="true"></i>
                                        @Html.Label("HospitalContactPersonEmail", "Contact Person Email")
                                        @Html.TextBoxFor(model => model.HospitalContactPersonEmail, new { @class = "form-control input-default borderclr", Maxlength = 30, id = "txthospitalcontactpersonemail" })
                                        @Html.ValidationMessageFor(model => model.HospitalContactPersonEmail, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                                        <i class="fa fa-envelope-o" aria-hidden="true"></i>
                                        @Html.Label("HospitalEmail", "Email")
                                        @Html.TextBoxFor(model => model.HospitalEmail, new { @class = "form-control input-default borderclr", Maxlength = 30, id = "txthospitalemail" })
                                        @Html.ValidationMessageFor(model => model.HospitalEmail, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                                        <i class="fa fa-sticky-note" aria-hidden="true"></i>
                                        @Html.Label("PatientIdStartWith", "Patient Id Start With")<span style="padding-left:2px;color:red">*</span>
                                        @Html.TextBoxFor(model => model.PatientIdStartWith, new { @class = "form-control input-default borderclr", Maxlength = 255, id = "txtpatientidstartwith" })
                                        @Html.ValidationMessageFor(model => model.PatientIdStartWith, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                                        <i class="fa fa-sticky-note" aria-hidden="true"></i>
                                        @Html.Label("HospitalAddress", "Address")<span style="padding-left:2px;color:red">*</span>
                                        @Html.TextAreaFor(model => model.HospitalAddress, new { @class = "form-control input-default borderclr", Maxlength = 255, id = "txthospitaladdress" })
                                        @Html.ValidationMessageFor(model => model.HospitalAddress, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-row mt-1" style="padding-left: 1.25rem;">
                        <div class="form-group col-lg-3 col-md-6 col-sm-12">
                            <a href="@Url.Action("Index","Hospital")" class="btn btn-sm btn-outline-danger borderradius">Back</a>
                            <button type="submit" id="btnhospitalsave" class="btn btn-sm btn-outline-primary borderradius">Submit</button>
                            <button type="reset" class="btn btn-outline-secondary btn-sm borderradius">Clear</button>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</body>
</html>
@section scripts {
    <script src="~/Scripts/Hospital/Hospital.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#page_name").text("Edit Hospital,");
        });
    </script>
}

SwasiHealthCare/SwasiHealthCare.Service/Views/Hospital/Index.cshtml
@model List<SwasiHealthCare.Model.HospitalModel>
@{
    ViewBag.Title = "Hospital List";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
    List<SwasiHealthCare.Data.Entities.AccessRights> rights =
     (List<SwasiHealthCare.Data.Entities.AccessRights>)Session["AccessRights"];
    var roleid = Convert.ToInt64(Session["RoleId"]);
}
<div class="row clearfix">
    <div class="col-sm-12">
        <div class="card">
            <div class="body">
                <form>
                    <div class="input-group" style="width:900px">
                        <input type="text" class="form-control" id="searchhospital" placeholder="Search here...">
                        <div class="input-group-append">
                            <span class="input-group-text" id="search-mail"><i class="icon-magnifier"></i></span>
                        </div>
                        @if ((roleid == 4 || roleid == 3) && rights.Where(x => x.MenuId == 9 && x.IsCreate).Any())
                        {
                        <div id="z_button" tabindex="0">
                            <div id="z_plus"><a href="@Url.Action("NewHospital", "Hospital")"><span style="color:#ffffff">+</span></a></div>
                        </div>
                        }
                        else if (roleid == 2 || roleid == 1)
                        {
                        <div id="z_button" tabindex="0">
                            <div id="z_plus"><a href="@Url.Action("NewHospital", "Hospital")"><span style="color:#ffffff">+</span></a></div>
                        </div>
                        }
                    </div>
                </form>
            </div>
        </div>
        <div class="table-responsive" id="hospital_list">
            <table class="table table-hover table-custom spacing5">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Code</th>
                        <th>Address</th>
                        <th>Contact Person Name</th>
                        <th>Email</th>
                        <th>Created Date</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>

                    @{
                        var index = 1;
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>@index</td>
                                <td>
                                    <a href="javascript:void(0);" title=""> @item.HospitalName</a>
                                    <div>@item.HospitalMobilNumber</div>
                                    <div>@item.LandlineNumber</div>
                                </td>
                                <td>@item.HospitalCode</td>
                                <td>@item.HospitalAddress</td>
                                <td>@item.HospitalContactPersonName</td>
                                <td>@item.HospitalEmail</td>
                                <td>@item.HospitalCreatedDate.ToString("MM/dd/yyyy")</td>
                                <td>
                                    @if (item.HospitalStatus)
                                    {
                                        <button type="button" class="btn btn-default btn-sm" onclick="ChangeHospitalStatus(@item.HospitalId,false)" style="color:#82b440; cursor:pointer" ; data-toggle="modal" data-target="#exampleModalCenter" title="Change User Status"><i class="fa fa-check-circle"></i></button>
                                    }
                                    else
                                    {
                                        <button type="button" class="btn btn-default btn-sm" onclick="ChangeHospitalStatus(@item.HospitalId,true)" style="color:#FF2A2A;cursor:pointer" ; data-toggle="modal" data-target="#exampleModalCenter" title="Change User Status"><i class="fa fa-times-circle"></i></button>
                                    }
                                    @if ((roleid == 4 || roleid == 3) && rights.Where(x => x.MenuId == 9 && x.IsEdit).Any())
                                    {
                                        <button onclick="location.href='@Url.Action("EditHospital", "Hospital",new {HospitalId=item.HospitalId })'" ; type="button" style="color:#0094ff; cursor:pointer" class="btn btn-default btn-sm" title="Edit"><i class="fa fa-pencil"></i></button>

                                    }
                                    else if (roleid == 2 || roleid == 1)
                                    {
                                        <button onclick="location.href='@Url.Action("EditHospital", "Hospital",new {HospitalId=item.HospitalId })'" ; type="button" style="color:#0094ff; cursor:pointer" class="btn btn-default btn-sm" title="Edit"><i class="fa fa-pencil"></i></button>

                                    }
                                    @if ((roleid == 4 || roleid == 3) && rights.Where(x => x.MenuId == 9 && x.IsDelete).Any())
                                    {
                                        <button type="button" style="color: #3e062d; cursor:pointer" ; class="btn btn-default btn-sm" title="Delete" onclick="RemoveHospital(@item.HospitalId)" data-toggle="modal" data-target="#exampleModalCenter"><i class="fa fa-trash-o"></i></button>
                                    }
                                    else if (roleid == 2 || roleid == 1)
                                    {
                                        <button type="button" style="color: #3e062d; cursor:pointer" ; class="btn btn-default btn-sm" title="Delete" onclick="RemoveHospital(@item.HospitalId)" data-toggle="modal" data-target="#exampleModalCenter"><i class="fa fa-trash-o"></i></button>
                                    }

                                </td>
                            </tr>
                            index++;
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" style="border-radius: 9px;">
            <div class="modal-header">
                <div><h6 class="modal-title" id="exampleModalCenterTitle"></h6></div>
            </div>
            <div class="modal-body">
                <div id="confirmmsg"></div>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-outline-primary borderradius" id="ActionStatus" onclick="HospitalStatus()">Save changes</a>
                <a href="#" class="btn btn-outline-primary borderradius" id="ActionDelete" onclick="DeleteHospital()">Save changes</a>
                <a href="@Url.Action("Index", "Hospital")" class="btn btn-outline-secondary borderradius">Close</a>
                <input type="hidden" id="hiddenhospitalid" />
                <input type="hidden" id="hiddenstatus" />
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script src="~/Scripts/Hospital/Hospital.js"></script>
    <script>
        $(document).ready(function () {
            $("#page_name").text("Hospital Details,");

            $("#searchhospital").on("keyup", function () {
                var value = $(this).val();

                $("table tr").each(function (index) {
                    debugger;
                    if (index != 0) {

                        $row = $(this);
                        var id = $row.find("td:eq(1)").text();

                        if (id.indexOf(value) != 0) {
                            $(this).hide();
                        }
                        else {
                            $(this).show();
                        }
                    }
                });
            });
        });
    </script>
}

SwasiHealthCare/SwasiHealthCare.Service/Views/Hospital/NewHospital.cshtml
@model SwasiHealthCare.Model.HospitalModel
@{
    ViewBag.Title = "New Hospital";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<html>
<head>
</head>
<body>
    <div class="card w-100 shadow-sm border-0">
        <div class="card-body p-3">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div>
                    <div class="tab-content" id="nav-tabContent">
                        <div class="" id="nav-newsystem" role="tabpanel" aria-labelledby="nav-orginal-tab" style="overflow-y: auto;">
                            <div class="card-body">
                                <div class="form-row">
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                                        <i class="fa fa-sort-numeric-asc" aria-hidden="true"></i>
                                        @Html.Label("HospitalCode", "Hospital Code")<span style="padding-left:2px;color:red">*</span>
                                        @Html.TextBoxFor(model => model.HospitalCode, new { @class = "form-control input-default borderclr", Maxlength = 20, id = "txthospitalcode" })
                                        @Html.ValidationMessageFor(model => model.HospitalCode, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                                        <i class="fa fa-address-book" aria-hidden="true"></i>
                                        @Html.Label("HospitalName", "Hospital Name")<span style="padding-left:2px;color:red">*</span>
                                        @Html.TextBoxFor(model => model.HospitalName, new { @class = "form-control input-default borderclr", Maxlength = 30, id = "txthospitalname" })
                                        @Html.ValidationMessageFor(model => model.HospitalName, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                                        <i class="fa fa-phone" aria-hidden="true"></i>
                                        @Html.Label("HospitalMobilNumber", "Mobile Number")<span style="padding-left:2px;color:red">*</span>
                                        @Html.TextBoxFor(model => model.HospitalMobilNumber, new { @class = "form-control input-default borderclr", Maxlength = 10, id = "txthospitalmobilnumber" })
                                        @Html.ValidationMessageFor(model => model.HospitalMobilNumber, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                                        <i class="fa fa-mobile" aria-hidden="true"></i>
                                        @Html.Label("LandlineNumber", "Landline Number")
                                        @Html.TextBoxFor(model => model.LandlineNumber, new { @class = "form-control input-default borderclr", Maxlength = 10, id = "txtlandlinenumber" })
                                        @Html.ValidationMessageFor(model => model.LandlineNumber, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                                        <i class="fa fa-navicon" aria-hidden="true"></i>
                                        @Html.Label("HospitalContactPersonName", "Contact Person Name")<span style="padding-left:2px;color:red">*</span>
                                        @Html.TextBoxFor(model => model.HospitalContactPersonName, new { @class = "form-control input-default borderclr", Maxlength = 30, id = "txthospitalcontactpersonname" })
                                        @Html.ValidationMessageFor(model => model.HospitalContactPersonName, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                                        <i class="fa fa-envelope" aria-hidden="true"></i>
                                        @Html.Label("HospitalContactPersonEmail", "Contact Person Email")
                                        @Html.TextBoxFor(model => model.HospitalContactPersonEmail, new { @class = "form-control input-default borderclr", Maxlength = 30, id = "txthospitalcontactpersonemail" })
                                        @Html.ValidationMessageFor(model => model.HospitalContactPersonEmail, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                                        <i class="fa fa-envelope-o" aria-hidden="true"></i>
                                        @Html.Label("HospitalEmail", "Email")
                                        @Html.TextBoxFor(model => model.HospitalEmail, new { @class = "form-control input-default borderclr", Maxlength = 30, id = "txthospitalemail" })
                                        @Html.ValidationMessageFor(model => model.HospitalEmail, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                                        <i class="fa fa-sticky-note" aria-hidden="true"></i>
                                        @Html.Label("PatientIdStartWith", "Patient Id Start With")<span style="padding-left:2px;color:red">*</span>
                                        @Html.TextBoxFor(model => model.PatientIdStartWith, new { @class = "form-control input-default borderclr", Maxlength = 255, id = "txtpatientidstartwith" })
                                        @Html.ValidationMessageFor(model => model.PatientIdStartWith, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                                        <i class="fa fa-sticky-note" aria-hidden="true"></i>
                                        @Html.Label("HospitalAddress", "Address")<span style="padding-left:2px;color:red">*</span>
                                        @Html.TextAreaFor(model => model.HospitalAddress, new { @class = "form-control input-default borderclr", Maxlength = 255, id = "txthospitaladdress" })
                                        @Html.ValidationMessageFor(model => model.HospitalAddress, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-row mt-1" style="padding-left: 1.25rem;">
                        <div class="form-group col-lg-3 col-md-6 col-sm-12">
                            <a href="@Url.Action("Index","Hospital")" class="btn btn-sm btn-outline-danger borderradius">Back</a>
                            <button type="submit" id="btnhospitalsave" class="btn btn-sm btn-outline-primary borderradius">Submit</button>
                            <button type="reset" class="btn btn-outline-secondary btn-sm borderradius">Clear</button>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</body>
</html>
@section scripts {
    <script src="~/Scripts/Hospital/Hospital.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#page_name").text("New Hospital,");
        });
    </script>
}